### ISSUE TITLE
Non-Nvdida support

### ISSUE THREAD

**Issue by metinc** [lupoglaz/GodotAIGym#10]
I see this project uses CUDA. Is there any way to disable CUDA and use this on an AMD machine?

**Comment by lupoglaz** [comment]
Yes, that's a problem. I was using pytorch to train the models, there seems to be a way to install it with amd gpu: https://github.com/aieater/rocm_pytorch_informations

**Comment by lupoglaz** [comment]
Another way to avoid GPU is to use only-cpu pytorch distribution:
`conda install pytorch torchvision torchaudio cpuonly -c pytorch`

Godot module and python module themselves do not depend on CUDA libraries and should compile.

**Comment by metinc** [comment]
Thanks. I tried setting up ROCm but installation failed and I had to reinstall Ubuntu. Not sure what went wrong. For now I will try the CPU only version. If performace is too bad I might try to set this up on my Windows machine where I have an Nvidia GPU.

**Comment by metinc** [comment]
I was able to train the InvPendulum without Cuda. All I had to do was to change any references to Cuda in DDGP.py and main.py to Cpu.
