### ISSUE TITLE
Shared memory crashes in Godot 3.2

### ISSUE THREAD

**Issue by restrada1** [lupoglaz/GodotAIGym#3]
I was able to compile and run GodotGymAI successfully on my system (Ubuntu 18.0, Python 3.8) using Godot 3.1, but it crashes for Godot 3.2. Specifically, in Godot 3.2 the shared memory module throws the following exception when I call the getFloatArray() function:

"Dynamic exception type: boost::interprocess::interprocess_exception std::exception::what: No such file or directory"

**Comment by lupoglaz** [comment]
Hello, thank you for opening this issue. Dev branch contains the code that runs with godot 3.2, but there are some changes needed in documentation. I'll try to finish it today/tomorrow.

**Comment by lupoglaz** [comment]
Please checkout current master branch. it was tested with godot 3.2 & debug exporting templates
