### ISSUE TITLE
Typo in Tutorial documentation

### ISSUE THREAD

**Issue by tybrs** [lupoglaz/GodotAIGym#4]
Awesome project! I believe there is a small typo with "shows" here: https://github.com/lupoglaz/GodotGymAI/blob/f55e245dbb344c2febefc7a9787b8bedc11e4c36/docs/tutorial.html#L132

Cheers!

**Comment by lupoglaz** [comment]
Thank you, corrected with 84aec4927d9289803f12c447bb2ba2361f1261f2
